config/routes.rb
NeilYoungOrg::Application.routes.draw do
  devise_for :users

  resources :links do
    resources :broken_link_reports, :as => :reports
  end

  namespace :admin do
    resources :links do
      member do
        put :confirm_broken
        put :deny_broken
      end
    end
  end

  root :to => "links#index"
end

app/models/broken_link_report.rb
class BrokenLinkReport < ActiveRecord::Base

  belongs_to :link

  scope :reported, where(:state => "reported")

  state_machine :state, :initial => :reported do
    event :confirm do
      transition :reported => :confirmed
    end
    event :deny do
      transition :reported => :denied
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :links

  default_scope order(:sort_order)
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates_presence_of :url, :title, :description

  belongs_to :category
  belongs_to :verifier, :class_name => "User"
  belongs_to :creator, :class_name => "User"
  has_many :broken_link_reports, :conditions => { :state => "reported" }

  scope :visible, where(:state => "accepted")
  scope :submitted, where(:state => "submitted")

  state_machine :state, :initial => :submitted do
    event :accept do
      transition :submitted => :accepted
    end
    event :deny do
      transition :submitted => :denied
    end
    event :confirm_broken do
      transition any => :broken
    end

    after_transition any => :broken do |link|
      link.broken_link_reports.each.map(&:confirm!)
    end
  end

  def self.reported
    BrokenLinkReport.reported.collect(&:link).uniq
  end

  def deny_broken!
    broken_link_reports.each.map(&:deny!)
  end

end

app/models/role.rb
class Role < ActiveRecord::Base

  validates_presence_of :name
  has_and_belongs_to_many :users

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  # Manually disabled until needed:
  #:registerable, :recoverable,
  devise :database_authenticatable,
         :rememberable,
         :trackable,
         :validatable,
         :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  validates_presence_of :name

  has_and_belongs_to_many :roles

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/admin/links_controller.rb
class Admin::LinksController < Admin::ResourcesController

  def index
    @reported_links = Link.reported
    @link = Link.new(:state => "accepted")
  end

  def update
    state_changed = accept_or_deny!
    update! { redirect_path(state_changed) }
  end

  def create
    @link = Link.new(params[:link])
    @link.accept!
    create! { admin_links_path }
  end

  def confirm_broken
    resource.confirm_broken!
    redirect_to :back
  end

  def deny_broken
    resource.deny_broken!
    redirect_to :back
  end

  protected

  def collection
    @links ||= end_of_association_chain.submitted
  end

  private

  def accept_or_deny!
    case params[:commit]
    when I18n.t("admin.links.form.accept")
      resource.accept!
    when I18n.t("admin.links.form.deny")
      resource.deny!
    end
  end

  def redirect_path(state_changed)
    if state_changed and link = Link.submitted.first
      edit_admin_link_path(link)
    else
      admin_links_path
    end
  end

end

app/controllers/admin/resources_controller.rb
class Admin::ResourcesController < Admin::ApplicationController
  inherit_resources
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/broken_link_reports_controller.rb
class BrokenLinkReportsController < ResourcesController
  belongs_to :link

  def create
    create! { root_path }
  end
end

app/controllers/links_controller.rb
class LinksController < ResourcesController

  def create
    create! { root_path }
  end

  protected

  def build_resource
    @link = super
    @link.creator = current_user if user_signed_in?
    @link
  end

  def collection
    @links ||= end_of_association_chain.visible
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  inherit_resources
end

app/helpers/admin/links_helper.rb
module Admin::LinksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/broken_link_reports_helper.rb
module BrokenLinkReportsHelper
end

app/views/admin/links/_form.html.haml
= simple_form_for [:admin, @link] do |form|
  = render "shared/links/form", :form => form
  = form.input :verifier_id, :as => :hidden, :input_html => { :value => current_user.id }
  = form.submit
  - if @link.submitted?
    = form.submit t(".accept")
    = form.submit t(".deny")

app/views/admin/links/edit.html.haml
= render 'form'

app/views/admin/links/index.html.haml
= render 'form'

- collection.each do |link|
  = link_to link.title, edit_admin_link_path(link)
  - if link.creator
    = "(#{link.creator.name})"

- @reported_links.each do |link|
  = link.title
  = link_to t(".confirm"), confirm_broken_admin_link_path(link), :method => :put
  = link_to t(".deny"), deny_broken_admin_link_path(link), :method => :put

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title neilyoung.org
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    - if flash[:notice]
      .flash.notice= flash[:notice]
    - if flash[:error]
      .flash.notice= flash[:error]
    - if user_signed_in?
      = link_to t(".logout"), destroy_user_session_path, :method => :delete
    = yield

app/views/links/index.html.haml
- collection.each do |link|
  = link.title
  = link_to t(".edit"), edit_admin_link_path(link) if user_signed_in?
  = link_to t(".report_broken.title"), link_reports_path(link), :method => :post

app/views/links/new.html.haml
= simple_form_for @link do |form|
  = render "shared/links/form", :form => form
  = form.submit

app/views/shared/links/_form.html.haml
= form.input :url
= form.input :title
= form.input :description
= form.input :poster_name
= form.input :poster_email
= form.association :category